### ISSUE TITLE
Cannot build rekapi

### ISSUE THREAD

**Issue by MeerKatDev** [jeremyckahn/rekapi#64]
After I use browserify to make a build.js file, I get this on the browser console:
```
bundle.js:3 Uncaught TypeError: Cannot read property 'style' of null
     at bundle.js:3
    at Object.<anonymous> (bundle.js:3)
    at t (bundle.js:3)
    at Object.<anonymous> (bundle.js:3)
    at t (bundle.js:3)
    at bundle.js:3
    at bundle.js:3
     at bundle.js:3
     at Object.1.shifty (bundle.js:3)
     at o (bundle.js:1)
(anonymous) @ bundle.js:3
(anonymous) @ bundle.js:3
t @ bundle.js:3
(anonymous) @ bundle.js:3
t @ bundle.js:3
(anonymous) @ bundle.js:3
(anonymous) @ bundle.js:3
(anonymous) @ bundle.js:3
1.shifty @ bundle.js:3
o @ bundle.js:1
(anonymous) @ bundle.js:1
3.rekapi @ bundle.js:10
o @ bundle.js:1
r @ bundle.js:1
(anonymous) @ bundle.js:1
jquery-3.3.1.min.js:2 jQuery.Deferred exception: rekapi is not defined ReferenceError: rekapi is not defined
    at HTMLDocument.<anonymous> (http://127.0.0.1/edsa-projects/Animodulo/:696:19)
    at l (http://127.0.0.1/.../js/jquery-3.3.1.min.js:2:29375)
    at c (http://127.0.0.1/.../js/jquery-3.3.1.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2
jquery-3.3.1.min.js:2 Uncaught ReferenceError: rekapi is not defined
    at HTMLDocument.<anonymous> ((index):696)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
```

the errors below the first come from a line where I try to do
```
$(function(){
 var lib = rekapi;
});
```

Additionally, I can't build with the procedure described in the readme of this project, it just gives 
missing script: build

**Comment by jeremyckahn** [comment]
Hi @MeerKatDev, thanks for opening an issue! It's not immediately clear to me what the issue might be. I haven't used Browserify, but I imagine that it should work similarly to Webpack (which Rekapi uses) when it comes to loading the library.

I'm wondering if Shifty (a dependency of Rekapi) needs to be explicitly loaded first in your environment? That should be automatic in environments with a proper bundler (like Webpack), but it isn't in some such as the browser where the individual JS files are loaded via `<script>` tags. Take a look at this CodePen: https://codepen.io/jeremyckahn/pen/vvQVVp?editors=1111

In that pen, I'm explicitly loading these two files in this order:

* https://unpkg.com/shifty@2.6.1/dist/shifty.js
* https://unpkg.com/rekapi@2.2.1/dist/rekapi.js

And this code works as expected:

```js
const { Rekapi } = rekapi;

console.log(Rekapi);
```

I'm realizing that this isn't mentioned anywhere in the README... I'll update that once we get to the bottom of this issue.

> Additionally, I can't build with the procedure described in the readme of this project, it just gives
missing script: build

This is strange to me; it almost sounds like you're using an old version of Rekapi. Could you please check the versions of Rekapi and Shifty you're loading? The latest version of Rekapi is 2.2.1, and Shifty is 2.6.1.

**Comment by jeremyckahn** [comment]
@MeerKatDev did you get a chance to take another look at this?

**Comment by jeremyckahn** [comment]
Closing due to inactivity.
